[log]
#INFO,WARN,ERROR,DEBUG
level = "DEBUG"
logfile = "./mon/dev/log/sfu.log"

[auth.jwt]
enabled = true
key = "SecretValueReplaceThis"
defaultexpiretime = 604800  # 1 week not implemented et jet

[metric.prometheus]
enable = true
endpoint = "/metrics" # Endpoint where the Prometheus metrics are delivered
