[instance]
https = false
domain = "localhost:8080"
user = "root@localhost:9000"
pass = ""
registerToken = "this-token-must-be-changed-in-public"
client = ""


[rtp]
iceServer = [{ urls = ["stun:stun.l.google.com:19302"] }]
