version: "3"

networks:
  monitoring:

services:
  loki:
    image: grafana/loki:2.8.2
    volumes:
      - ./etc/loki-config.yml:/etc/loki/loki-config.yml
    ports:
      - "3100:3100"
      - "9093:9093"
    command: -config.file=/etc/loki/loki-config.yml
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:2.8.2
    volumes:
      - ./etc/promtail-config.yml:/etc/promtail/config.yml
      - ./log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yml", "--auth.enabled=false" ]
    volumes:
      - ./etc/tempo-config.yml:/etc/tempo.yml
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
    networks:
      - monitoring

  tempo-query:
    image: grafana/tempo-query:0.7.0
    environment:
      - BACKEND=tempo:3200
    volumes:
      - ./etc/tempo-query-config.yml:/etc/tempo-query.yaml
    ports:
      - "16686:16686"  # jaeger-ui
    depends_on:
      - tempo
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./etc/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3011:3000"
    depends_on:
      - tempo
      - loki
      - prometheus
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    command:
      --web.enable-remote-write-receiver
      --enable-feature=exemplar-storage
    volumes:
      - ./etc/prometheus-config.yml:/etc/prometheus-config.yml
    entrypoint:
      - /bin/prometheus
      - --config.file=/etc/prometheus-config.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitoring
