name: Run Tests

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Build
        run: make build
      - name: Test with Go
        run: make test-git
      - name: Upload Go test results
        uses: actions/upload-artifact@v5
        with:
          name: Go-results
          path: TestResults.json
