name: Run Tests

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Build
        run: make build
      - name: Test with Go
        uses: robherley/go-test-action@v0.2.0
